version: '3.3'
services:
  mysql:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    command: mysqld --sql_mode=""
    volumes:
      - ./db/U_VOCAB_SCHEMA.sql:/docker-entrypoint-initdb.d/U_VOCAB_SCHEMA.sql
