spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/U_VOCAB
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl