CREATE DATABASE U_VOCAB;
USE U_VOCAB;

CREATE TABLE USER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOGIN varchar(50),
    EMAIL varchar(100)
);

CREATE TABLE VOCABULARY
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WORD VARCHAR(155)
);

-- user
INSERT INTO USER (LOGIN, EMAIL) VALUES ('robson@uvocab.education', 'robson@uvocab.education');


-- vocabulary
INSERT INTO VOCABULARY (WORD) VALUES ('car');
INSERT INTO VOCABULARY (WORD) VALUES ('house');
INSERT INTO VOCABULARY (WORD) VALUES ('home');
INSERT INTO VOCABULARY (WORD) VALUES ('mobile');
INSERT INTO VOCABULARY (WORD) VALUES ('computer');
INSERT INTO VOCABULARY (WORD) VALUES ('notebook');
INSERT INTO VOCABULARY (WORD) VALUES ('laptop');
INSERT INTO VOCABULARY (WORD) VALUES ('show');
INSERT INTO VOCABULARY (WORD) VALUES ('concert');
INSERT INTO VOCABULARY (WORD) VALUES ('pay');
INSERT INTO VOCABULARY (WORD) VALUES ('play');
INSERT INTO VOCABULARY (WORD) VALUES ('soccer');
INSERT INTO VOCABULARY (WORD) VALUES ('guitar');
INSERT INTO VOCABULARY (WORD) VALUES ('bat');
INSERT INTO VOCABULARY (WORD) VALUES ('lion');
INSERT INTO VOCABULARY (WORD) VALUES ('dog');
INSERT INTO VOCABULARY (WORD) VALUES ('cat');
INSERT INTO VOCABULARY (WORD) VALUES ('bird');
INSERT INTO VOCABULARY (WORD) VALUES ('music');
INSERT INTO VOCABULARY (WORD) VALUES ('two');
INSERT INTO VOCABULARY (WORD) VALUES ('apple');
INSERT INTO VOCABULARY (WORD) VALUES ('pineapple');
INSERT INTO VOCABULARY (WORD) VALUES ('pen');
INSERT INTO VOCABULARY (WORD) VALUES ('pencil');
INSERT INTO VOCABULARY (WORD) VALUES ('book');
INSERT INTO VOCABULARY (WORD) VALUES ('clothes');
INSERT INTO VOCABULARY (WORD) VALUES ('door');
INSERT INTO VOCABULARY (WORD) VALUES ('shirt');
INSERT INTO VOCABULARY (WORD) VALUES ('t-shirt');
INSERT INTO VOCABULARY (WORD) VALUES ('cup');


