CREATE DATABASE U_VOCAB;
USE U_VOCAB;

CREATE TABLE USER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOGIN varchar(50),
    EMAIL varchar(100)
);

CREATE TABLE VOCABULARY
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WORD VARCHAR(155)
);

INSERT INTO USER (LOGIN, EMAIL) VALUES ('robson@uvocab.education', 'robson@uvocab.education');