name: Uvocab API

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 20
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
      - name: Build and analyze
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build